#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
# The name of the custom HTTP header must be X-Served-By

apt update
apt install -y nginx

echo "Hello World" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root /var/www/html;
    index index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
}" > /etc/nginx/sites-enabled/default

service nginx restart
