#!/bin/bash
# Creates a file and displays different out depending on signal

echo "$$" > /var/run/myscript.pid

cleanup_and_exit() {
    rm /var/run/myscript.pid
    exit
}

trap 'echo "Y U no love me?!";' SIGINT
trap 'echo "I hate the kill command" && cleanup_and_exit' SIGTERM
trap 'cleanup_and_exit' SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 2
done

