#!/usr/bin/env bash

# Loop from 1 to 10 and display different messages based on iteration
n=1

while [ $n -le 10 ]; do
    if [ $n -eq 4 ]; then
        echo "bad luck"
    elif [ $n -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((n++))
done
