#!/usr/bin/env bash

# Loop from 1 to 10 and display different messages

call=1
while [ $call -le 10 ];
do
    if [ $call -eq 4 ];
then
        echo "bad luck"
    elif [ $call -eq 8 ];
then
        echo "good luck"
    else
        echo "Best School"
    fi
    call=$((call + 1))
done
