#!/usr/bin/env bash
#Configures a ufw firewall to block all incoming traffic except for TCP ports 22, 443 and 80.

echo -e "Updating\n"

sudo apt-get update

echo -e "Installing UFW\n"

sudo apt-get install -y ufw

echo -e "configuring UFW...\n"


sudo ufw default deny incoming
sudo ufw default allow outgoing

sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443

sudo ufw enable

echo -e "Process Completed.\n"
